from fastapi import FastAPI, File, UploadFile, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
import os

app = FastAPI()

origins = [os.getenv("FRONTEND_URL", "http://localhost:5173")]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/")
async def root():
    return {"message": "Backend is running 🚀"}

@app.post("/upload")
async def upload_file(file: UploadFile = File(...)):
    contents = await file.read()  # raw bytes (PDF, DOCX, etc.)
    return {
        "filename": file.filename,
        "content_type": file.content_type,
        "size": len(contents),
    }

@app.post("/summarize")
async def summarize_text(request: dict):
    """
    Dummy API endpoint for text summarization
    Expected input: {"text": "text to summarize", "summary_type": "brief|detailed"}
    """
    try:
        text = request.get("text", "")
        summary_type = request.get("summary_type", "brief")
        
        if not text:
            raise HTTPException(status_code=400, detail="Text is required")
        
        # Dummy summarization logic
        if summary_type == "detailed":
            summary = f"Detailed summary: This is a comprehensive analysis of the provided text. {text[:100]}..."
        else:
            summary = f"Brief summary: {text[:50]}..."
        
        return {
            "summary": summary,
            "original_length": len(text),
            "summary_length": len(summary),
            "summary_type": summary_type
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/ask")
async def ask_question(request: dict):
    """
    Dummy API endpoint for asking questions about uploaded content
    Expected input: {"question": "question about content", "context": "optional context"}
    """
    try:
        question = request.get("question", "")
        context = request.get("context", "")
        
        if not question:
            raise HTTPException(status_code=400, detail="Question is required")
        
        # Dummy response logic
        answer = f"Based on the provided context, here's the answer to '{question}': This is a dummy response that would normally be generated by an AI model."
        
        return {
            "question": question,
            "answer": answer,
            "confidence": 0.85,
            "context_used": bool(context)
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))